### ISSUE TITLE
Question: How can I get a Shahaf's API key?

### ISSUE THREAD

**Issue by ofekashery** [NuclearGandhi/blich-android#1]

**Comment by ofekashery** [comment]
@NuclearGandhi help?

**Comment by ofekashery** [comment]
@NuclearGandhi help?

**Comment by NuclearGandhi** [comment]
To acquire a Shaha'fs API key you need to contact Shahaf themselves - [link](http://support.iscool.co.il/).
Please note that when I contacted them, they referred to the API key as TOKEN_API.
